import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { OrigamiGeneratedModule, OrigamiGeneratedSharedModule } from './generated/module.js';
import { OrigamiValidator, registerValidationChecks } from './origami-validator.js';
import { CustomScopeComputation } from './origami-scope.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type OrigamiAddedServices = {
    validation: {
        OrigamiValidator: OrigamiValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type OrigamiServices = LangiumServices & OrigamiAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const OrigamiModule: Module<OrigamiServices, PartialLangiumServices & OrigamiAddedServices> = {
    references:{
        ScopeComputation: (services) => new CustomScopeComputation(services)
    },
    validation: {
        OrigamiValidator: () => new OrigamiValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createOrigamiServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Origami: OrigamiServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        OrigamiGeneratedSharedModule
    );
    const Origami = inject(
        createDefaultModule({ shared }),
        OrigamiGeneratedModule,
        OrigamiModule
    );
    shared.ServiceRegistry.register(Origami);
    registerValidationChecks(Origami);
    return { shared, Origami };
}
